### PR TITLE
Added animations on hover and when head is active!

### PR DESCRIPTION
**Pull request by abitsalihu**
Hey @Suman373,  I changed the font size to go with the theme, and changed animations on hover and on active state

Below are two videos that show what the website looks on the hover state and active state:

Hover state:

https://user-images.githubusercontent.com/94648837/191871629-9b720e2d-c6cb-4bf2-8850-c366f528b895.mov

Active state:

https://user-images.githubusercontent.com/94648837/191871646-7b66fca9-b6eb-44e2-ae82-557387a36cd8.mov

### CODE REVIEW

**Comment by Suman373** [comment]
Your animation looks awesome. Good job. Although, there should be few changes:
1. The bg color is too bright and not in contrast with the iron man's mask, pls look into it.
2. The footer font size should be reduced, along with the capitalised font-style (family).

Make your pr on the issue-2 branch

**Comment by abitsalihu** [comment]
Hey @Suman373, what color would you like the background to be when clicked? I honestly love the contrast between them as that bright color give life to the whole website, but please tell me what color would like to have as background.

As per front I will reduce them.

**Comment by abitsalihu** [comment]
@Suman373 I changed the footer to "sans-serif" so it can be much easier read, since your name is there. 
I also changed the font size of both the "header" and "footer" for better UI.
As per the background I left it as is, because I couldn't find any other better color than the one I put, but you can change it to whatever you think it suits best after merge.

Awesome "Iron Man" drawing btw. :)

**Review by Suman373 — APPROVED** [review]

**Comment by Suman373** [comment]
Alright! I think it is good for now. Feel free to create issue if you want to improve something!
Keep contributing !

**Pull request merged**
