### PR TITLE
changes made

### PR DESCRIPTION
**Pull request by ujjawalD07**
### **Following changes made-:**

1.  Added bootstrap for font styling
2. Changed background color
3. Added JavaScript function for speaking animation
4. Minor changes in the gradient and color of the mask

### Before

before

### After

after

### CODE REVIEW

**Comment by Suman373** [comment]
What kind of animation u have added? Could u show an example?

**Comment by ujjawalD07** [comment]
@Suman373 


https://user-images.githubusercontent.com/87711904/191988322-2a7382d6-0dda-425d-ab4a-eae1cabb1743.mp4

**As you click on the helmet, it's mouth starts moving as if it is speaking until Jarvis is done talking. Everything happens automatically, no need to start or stop or hover.**

**Comment by Suman373** [comment]
The video doesn't have any sound, though the animation for the mouth looks cool!

**Comment by Suman373** [comment]
Make your PR on the issue-1 branch.

**Comment by ujjawalD07** [comment]
Just did.

**Comment by Suman373** [comment]
Hey @ujjawalD07 , someone else has worked on this issue. The pr with the solution has been merged. It doesn't mean you cant contribute anymore.
Pull the changes to your local, run the site and see if there are any tweaks u want to make. Create issue and pr solution accordingly. ! All the best !

**Pull request closed without merging**
